name: Pytest

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: DEBUG
      UV_NO_SYNC: 1
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"
          enable-cache: true

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked

      - name: Run all tests
        run: uv run pytest
